---
version: 2
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  # apt_packages: # Keep in sync with Dockerfile
  #   - qt6-base-dev
  #   - qt6-tools-dev
  #   - qt6-tools-dev-tools
  #   - qt6-wayland
  #   - qt6-l10n-toolslibclang
  jobs:
    post_create_environment:
      - pip install pdm
    post_install:
      - pdm use -f $READTHEDOCS_VIRTUALENV_PATH
      - pdm install

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false # false until we want to have it install all deps and build
