---
name: Update dependencies
# Dependabot does not recognise PDM so we use the PDM version

on:
  # schedule:
  #   - cron: "0 0 1 * *" # monthly
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update dependencies
        uses: pdm-project/update-deps-action@main
